{{- /*
Copyright Dominik Schlosser
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if or (not .Values.seed.existingSecret) (and (eq .Values.storage.type "postgresql") .Values.externalDatabase.password (not .Values.externalDatabase.existingSecret)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eudi-dev.secretName" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: wallet
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if not .Values.seed.existingSecret }}
  seed: {{ .Values.seed.value | toString | b64enc | quote }}
  {{- end }}
  {{- if and (eq .Values.storage.type "postgresql") .Values.externalDatabase.password (not .Values.externalDatabase.existingSecret) }}
  database-password: {{ .Values.externalDatabase.password | b64enc | quote }}
  {{- end }}
{{- end }}
